name: ci

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@v18

      - name: Build sherpa-onnx
        run: nix build .#sherpa-onnx --no-link --print-build-logs
